name: 'Setup NodeJS environment with pnpm.'
description: 'Checks out the repository, sets up NodeJS and pnpm and installs dependencies.'
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
    
    - name: Setup NodeJS
      uses: actions/setup-node@v6
      with:
        node-version-file: 'package.json'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
