name: Checkout with NodeJS and install node_modules
author: ExampleWasTaken Studios
description: A combination of actions/checkout@v4 and actions/setup-node@v4 and npm install. It expects to be used in workflows triggered by `pull_request`.

inputs:
  node-version:
    description: The node version you wish to install. This is passed directly to actions/setup-node.
    required: true
    

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install dependencies
      run: npm ci
      shell: bash
